//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRegistroAspirantes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administradores
    {
        public short Id { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Correo { get; set; }
        public string Contrasenia { get; set; }
        public string TelefonoFijo { get; set; }
        public string TelefonoCelular { get; set; }
        public Nullable<int> IdCampus { get; set; }
        public byte IdRol { get; set; }
    
        public virtual Campus Campus { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
