//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRegistroAspirantes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RegistroAspirantesEntities : DbContext
    {
        public RegistroAspirantesEntities()
            : base("name=RegistroAspirantesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acciones> Acciones { get; set; }
        public virtual DbSet<AccionesAdministradores> AccionesAdministradores { get; set; }
        public virtual DbSet<Administradores> Administradores { get; set; }
        public virtual DbSet<Bancos> Bancos { get; set; }
        public virtual DbSet<Campus> Campus { get; set; }
        public virtual DbSet<CampusCarreras> CampusCarreras { get; set; }
        public virtual DbSet<Carreras> Carreras { get; set; }
        public virtual DbSet<Generos> Generos { get; set; }
        public virtual DbSet<GradosEstudio> GradosEstudio { get; set; }
        public virtual DbSet<Localidades> Localidades { get; set; }
        public virtual DbSet<Paises> Paises { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Solicitantes> Solicitantes { get; set; }
    }
}
